[project]
name = "openclassrooms-project-09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "flake8>=7.3.0",
    "flake8-html>=0.4.3",
    "pillow>=12.1.0",
]
